// This file is automatically generated by generate_SV_file.m, 05-Nov-2024

	// connection lenght defines
	localparam int len = 12;

	// int Arrays with Constants
	localparam logic unsigned [31:0] networkStructure [2:0] = '{2,7,3};
	localparam logic unsigned [31:0] connnectionRange [3:0] = '{12,10,3,0};
	localparam logic signed [31:0] weights [43:0] = '{26790,-175,-131,8,67,4,36,-109,6646,85,-153,13,-16,25,4,-41,-16861,436,-15,-171,8842,293,252,-480,-28825,-23,-25,-14,15701,-62,62,92,-31597,-8,-45,-12,-19481,-14,31,-32,12036,249,34,-260};

	// mapping the 2D network to the 1D Array with the weights
	localparam logic [30:0] positions [0:7][1:2] = '{
		'{0,28},
		'{4,36},
		'{8,44},
		'{12,0},
		'{16,0},
		'{20,0},
		'{24,0},
		'{28,0}
	};
