// This file is automatically generated by generate_SV_file.m, 08-Nov-2024

	// connection lenght defines
	localparam int len = 12;
	// connection 2 downto 0 is the input of the neural network
	// connection 11 downto 10 is the output of the neural network

	// int Arrays with Constants
	localparam logic unsigned [31:0] networkStructure [2:0] = '{2,7,3};
	localparam logic unsigned [31:0] connnectionRange [3:0] = '{12,10,3,0};
	localparam logic signed [31:0] weights [43:0] = '{-11995,-247,58,40,-200,-100,178,-8,42433,-177,-101,-5,-16,55,-208,-100,-14083,489,394,-754,56491,155,58,-449,-33093,92,83,11,15146,-390,4,79,46894,19,18,-96,127804,-85,-165,-481,-52714,346,232,-310};

	// mapping the 2D network to the 1D Array with the weights
	localparam logic [30:0] positions [0:7][1:2] = '{
		'{0,28},
		'{4,36},
		'{8,44},
		'{12,0},
		'{16,0},
		'{20,0},
		'{24,0},
		'{28,0}
	};